services:
  app:
    build: .
    networks:
      - shared
    environment:
      MAX_UPLOAD_MB: 100
    volumes:
      - ./backend/src:/app/backend/src
    ports:
      - "8015:8000"

  test:
    build: .
    command: python -m unittest discover -s tests -v
    profiles: ["test"]

networks:
  shared:
    external: true
    name: shared-network
